version: "3.7"

services:

  app:
    build:
      args:
        user: bruh
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: bruh
    container_name: bruh-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./bruh/:/var/www
    networks:
      - bruh
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: bruh-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./bruh/:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - bruh

  postgres:
    image: postgres:alpine
    container_name: bruh-postgres
    hostname: '${POSTGRES_DB_HOST}'
    restart: unless-stopped
    user: postgres
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_DB_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_DB_USERNAME}'
      POSTGRES_DB: '${POSTGRES_DB_DATABASE}'
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
    networks:
      - bruh
    ports:
      - '${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}'
    healthcheck:
        test: pg_isready
        retries: 5
        timeout: 5s
        interval: 10s

  elastic:
    image: elasticsearch:7.17.0
    container_name: bruh-elastic
    hostname: elastic
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - network.bind_host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - 'elasticdata:/usr/share/elasticsearch/data'
    networks:
      - bruh
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    cap_add:
      - IPC_LOCK
networks:
  bruh:
    driver: bridge

volumes:
  postgresdata:
    driver: local
    external: false

  elasticdata:
    driver: local
    external: false
